export const carnivalCountries = [
  {
    country: "All Countries",
    locations: ["All Countries"],
    exampleAddress: {
      streetAddress: "All Countries",
      locality: "All Countries",
      subRegion: "All Countries",
      postalCode: "All Countries",
    },
  },
  {
    country: "Antigua and Barbuda",
    locations: ["Antigua"],
    exampleAddress: {
      streetAddress: "Fort Road",
      locality: "St. John's",
      subRegion: "St. John",
      postalCode: "N/A (Parish often sufficient)",
    },
  },
  {
    country: "Aruba",
    locations: ["Aruba"],
    exampleAddress: {
      streetAddress: "L.G. Smith Boulevard 142",
      locality: "Oranjestad",
      subRegion: "N/A",
      postalCode: "N/A",
    },
  },
  {
    country: "Australia",
    locations: ["Sydney (Likely)"],
    exampleAddress: {
      streetAddress: "10 Macquarie Street",
      locality: "Sydney",
      subRegion: "New South Wales",
      postalCode: "2000",
    },
  },
  {
    country: "Bahamas",
    locations: ["Bahamas"],
    exampleAddress: {
      streetAddress: "Bay Street",
      locality: "Nassau",
      subRegion: "New Providence",
      postalCode: "N-3005",
    },
  },
  {
    country: "Barbados",
    locations: ["Barbados"],
    exampleAddress: {
      streetAddress: "Broad Street",
      locality: "Bridgetown",
      subRegion: "St. Michael",
      postalCode: "BB11138",
    },
  },
  {
    country: "Belize",
    locations: ["Belize"],
    exampleAddress: {
      streetAddress: "Albert Street",
      locality: "Belize City",
      subRegion: "Belize District",
      postalCode: "N/A",
    },
  },
  {
    country: "Bermuda",
    locations: ["Bermuda"],
    exampleAddress: {
      streetAddress: "Front Street",
      locality: "Hamilton",
      subRegion: "Pembroke",
      postalCode: "HM 11",
    },
  },
  {
    country: "Bolivia",
    locations: ["Bolivia"],
    exampleAddress: {
      streetAddress: "Avenida Mariscal Santa Cruz",
      locality: "La Paz",
      subRegion: "La Paz Department",
      postalCode: "N/A (Postal codes exist but not always used)",
    },
  },
  {
    country: "Brazil",
    locations: ["Rio"],
    exampleAddress: {
      streetAddress: "Avenida Atlântica, 1702",
      locality: "Rio de Janeiro",
      subRegion: "Estado do Rio de Janeiro",
      postalCode: "22021-001",
    },
  },
  {
    country: "Canada",
    locations: ["Toronto", "Edmonton", "Montreal", "Ottawa"],
    exampleAddress: {
      streetAddress: "100 Queen Street West",
      locality: "Toronto",
      subRegion: "Ontario",
      postalCode: "M5H 2N2",
    },
  },
  {
    country: "Colombia",
    locations: ["Barranquilla"],
    exampleAddress: {
      streetAddress: "Calle 72 # 57 - 81",
      locality: "Barranquilla",
      subRegion: "Atlántico",
      postalCode: "080020",
    },
  },
  {
    country: "Curacao",
    locations: ["Curacao"],
    exampleAddress: {
      streetAddress: "Handelskade",
      locality: "Willemstad",
      subRegion: "N/A",
      postalCode: "N/A",
    },
  },
  {
    country: "Dominica",
    locations: ["Dominica"],
    exampleAddress: {
      streetAddress: "Bayfront",
      locality: "Roseau",
      subRegion: "St. George",
      postalCode: "N/A",
    },
  },
  {
    country: "France (Overseas Regions)",
    locations: ["Guadeloupe", "French Guiana", "Martinique"],
    exampleAddress: {
      streetAddress: "Rue Schoelcher",
      locality: "Pointe-à-Pitre (Guadeloupe)",
      subRegion: "Guadeloupe",
      postalCode: "97110",
    },
  },
  {
    country: "Germany",
    locations: ["Berlin"],
    exampleAddress: {
      streetAddress: "Unter den Linden 77",
      locality: "Berlin",
      subRegion: "Berlin",
      postalCode: "10117",
    },
  },
  {
    country: "Grenada",
    locations: ["Grenada", "Carriacou"],
    exampleAddress: {
      streetAddress: "Grand Anse",
      locality: "St. George's",
      subRegion: "St. George",
      postalCode: "N/A",
    },
  },
  {
    country: "Japan",
    locations: ["Soca in Japan (Likely Tokyo)"],
    exampleAddress: {
      streetAddress: "2-1-3 Shibuya",
      locality: "Shibuya-ku",
      subRegion: "Tokyo",
      postalCode: "150-8019",
    },
  },
  {
    country: "Jamaica",
    locations: ["Jamaica"],
    exampleAddress: {
      streetAddress: "24 Trafalgar Road",
      locality: "Kingston 5",
      subRegion: "St. Andrew",
      postalCode: "N/A (Postal zones exist)",
    },
  },
  {
    country: "Montserrat",
    locations: ["Montserrat"],
    exampleAddress: {
      streetAddress: "Parliament Street",
      locality: "Brades",
      subRegion: "N/A",
      postalCode: "N/A",
    },
  },
  {
    country: "Netherlands",
    locations: ["Rotterdam"],
    exampleAddress: {
      streetAddress: "Coolsingel 40",
      locality: "Rotterdam",
      subRegion: "Zuid-Holland",
      postalCode: "3011 AD",
    },
  },
  {
    country: "Panama",
    locations: ["Panama"],
    exampleAddress: {
      streetAddress: "Avenida Balboa",
      locality: "Panama City",
      subRegion: "Panamá Province",
      postalCode: "N/A (Postal codes exist)",
    },
  },
  {
    country: "Puerto Rico (USA)",
    locations: ["Puerto Rico"],
    exampleAddress: {
      streetAddress: "Calle Fortaleza 51",
      locality: "San Juan",
      subRegion: "San Juan",
      postalCode: "00901",
    },
  },
  {
    country: "St. Barthélemy",
    locations: ["St. Bart's"],
    exampleAddress: {
      streetAddress: "Rue de la République",
      locality: "Gustavia",
      subRegion: "N/A",
      postalCode: "97133",
    },
  },
  {
    country: "St. Kitts and Nevis",
    locations: ["St. Kitts", "Nevis"],
    exampleAddress: {
      streetAddress: "Bay Road",
      locality: "Basseterre (St. Kitts)",
      subRegion: "St. Kitts",
      postalCode: "N/A",
    },
  },
  {
    country: "St. Lucia",
    locations: ["St. Lucia"],
    exampleAddress: {
      streetAddress: "Bridge Street",
      locality: "Castries",
      subRegion: "Castries",
      postalCode: "N/A",
    },
  },
  {
    country: "St. Maarten (Dutch Side)",
    locations: ["St. Maarten"],
    exampleAddress: {
      streetAddress: "Front Street",
      locality: "Philipsburg",
      subRegion: "N/A",
      postalCode: "N/A",
    },
  },
  {
    country: "St. Vincent and the Grenadines",
    locations: ["St. Vincent"],
    exampleAddress: {
      streetAddress: "Bay Street",
      locality: "Kingstown",
      subRegion: "St. George",
      postalCode: "N/A",
    },
  },
  {
    country: "Saba (Netherlands)",
    locations: ["Saba"],
    exampleAddress: {
      streetAddress: "Main Road",
      locality: "The Bottom",
      subRegion: "Saba",
      postalCode: "N/A",
    },
  },
  {
    country: "Statia (Netherlands)",
    locations: ["Statia"],
    exampleAddress: {
      streetAddress: "Fort Oranje",
      locality: "Oranjestad",
      subRegion: "Sint Eustatius",
      postalCode: "N/A",
    },
  },
  {
    country: "Trinidad and Tobago",
    locations: ["Trinidad", "Tobago"],
    exampleAddress: {
      streetAddress: "Independence Square",
      locality: "Port of Spain",
      subRegion: "Trinidad",
      postalCode: "000000 (Typical Format)",
    },
  },
  {
    country: "United Arab Emirates",
    locations: ["Dubai"],
    exampleAddress: {
      streetAddress: "Sheikh Zayed Road",
      locality: "Dubai",
      subRegion: "Emirate of Dubai",
      postalCode: "N/A (Often P.O. Box or structured code)",
    },
  },
  {
    country: "United Kingdom",
    locations: ["Leeds", "Notting Hill (London)"],
    exampleAddress: {
      streetAddress: "1 City Square",
      locality: "Leeds",
      subRegion: "West Yorkshire",
      postalCode: "LS1 2ES",
    },
  },
  {
    country: "United States",
    locations: [
      "St. Croix",
      "New Orleans",
      "Alabama",
      "Tampa Bay",
      "Atlantic City",
      "Jersey City",
      "Delaware",
      "Raleigh",
      "Chicago",
      "Jacksonville",
      "San Francisco",
      "Orlando",
      "South Carolina",
      "Philadelphia",
      "Washington D.C. (Hookie Wknd DC)",
      "Hollywood",
      "Charlotte",
      "Charleston",
      "St. John",
      "Houston",
      "Norfolk",
      "Dallas",
      "Long Island",
      "Miami",
    ],
    exampleAddress: {
      streetAddress: "714 St. Peter Street",
      locality: "New Orleans",
      subRegion: "Louisiana",
      postalCode: "70116",
    },
  },
];
